import * as images from '@/Assets/Images';
export const appointments = [
  {
    title: 'Styling',
    price: 43,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: [],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: false,
    reviews: 85,
    time: '7:00 PM',
  },
  {
    title: 'Haircut & Styling',
    price: 4.43,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: ['Outdoor Option', 'Hair Accessories', 'Bang Trim'],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: false,
    reviews: 85,
    time: '7:00 PM',
  },
  {
    title: 'Conditioning',
    price: 4,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: [
      'Outdoor Option',
      'Hair Accessories',
      'Outdoor Option',
      'Hair Accessories',
      'Outdoor Option',
      'Hair Accessories',
    ],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: true,
    reviews: 30,
    time: '7:00 PM',
  },
  {
    title: 'Styling1',
    price: 43,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: [],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: false,
    reviews: 85,
    time: '7:00 PM',
  },
  {
    title: 'Haircut & Styling1',
    price: 4.43,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: ['Outdoor Option', 'Hair Accessories', 'Bang Trim'],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: false,
    reviews: 85,
    time: '7:00 PM',
  },
  {
    title: 'Conditioning1',
    price: 4,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: [
      'Outdoor Option',
      'Hair Accessories',
      'Outdoor Option',
      'Hair Accessories',
      'Outdoor Option',
      'Hair Accessories',
    ],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: true,
    reviews: 30,
    time: '7:00 PM',
  },
  {
    title: 'Styling2',
    price: 43,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: [],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: false,
    reviews: 85,
    time: '7:00 PM',
  },
  {
    title: 'Haircut & Styling2',
    price: 4.43,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: ['Outdoor Option', 'Hair Accessories', 'Bang Trim'],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: false,
    reviews: 85,
    time: '7:00 PM',
  },
  {
    title: 'Conditioning2',
    price: 4,
    date: '14 April, 2022 ',
    des: 'Golden Lotus Beauty Salon',
    add_ons: [
      'Outdoor Option',
      'Hair Accessories',
      'Outdoor Option',
      'Hair Accessories',
      'Outdoor Option',
      'Hair Accessories',
    ],
    name: 'Gregory Hayes',
    rating: 4,
    isConfirmed: false,
    isFreelace: true,
    reviews: 30,
    time: '7:00 PM',
  },
];

export const credits = [
  {
    heading: 'Pt 20',
    value: 'Coupon Unlocked',
    date: 'Expire on june 2023',
  },
  {
    heading: 'Pt 201',
    value: 'Coupon Unlocked1',
    date: 'Expire on june 2021',
  },
  {
    heading: 'Pt 22',
    value: 'Coupon Unlocked2',
    date: 'Expire on june 2022',
  },
  {
    heading: 'Pt 23',
    value: 'Coupon Unlocke3',
    date: 'Expire on june 2033',
  },
  {
    heading: 'Pt 24',
    value: 'Coupon Unlocked4',
    date: 'Expire on june 2024',
  },
  {
    heading: 'Pt 25',
    value: 'Coupon Unlocked5',
    date: 'Expire on june 2025',
  },
  {
    heading: 'Pt 26',
    value: 'Coupon Unlocked6',
    date: 'Expire on june 2026',
  },
  {
    heading: 'Pt 27',
    value: 'Coupon Unlocked7',
    date: 'Expire on june 2027',
  },
  {
    heading: 'Pt 28',
    value: 'Coupon Unlocked8',
    date: 'Expire on june 2028',
  },
  {
    heading: 'Pt 29',
    value: 'Coupon Unlocke9',
    date: 'Expire on june 2029',
  },
  {
    heading: 'Pt 30',
    value: 'Coupon Unlocked30',
    date: 'Expire on june 2030',
  },
  {
    heading: 'Pt 31',
    value: 'Coupon Unlocked31',
    date: 'Expire on june 2031',
  },
];

export const servicesData = [
  {name: 'Blowouts', price: 4.14, cover: images.blowouts},
  {name: 'Haircut', price: 4.4, cover: images.haircut},
  {name: 'Makeup', price: 4.14, cover: images.makeup},
];

export const offerData = [
  {name: 'Threading', price: 4.14, cover: images.threading},
  {name: 'Maskara', price: 4.4, cover: images.maskara},
  {name: 'Threading', price: 4, cover: images.threading},
  {name: 'Maskara', price: 4.04, cover: images.maskara},
];
export const packkagesData = [
  {
    name: 'Whole Body Relief Massage',
    price: 149.99,
    cover: images.package,
    desc: 'Available Only For 3 Days',
  },
  {
    name: 'facials & skin care treatments.',
    price: 85.99,
    cover: images.package,
    desc: 'Available Only For 3 Days',
  },
  {
    name: 'Whole Body Relief Massage',
    price: 149.99,
    cover: images.package,
    desc: 'Available Only For 3 Days',
  },
];

export const reviewsData = [
  {
    id: 1,
    image: images.user2,
    name: 'Matilda Brown',
    date: 'August 14, 2019',
    rating: 4,
    message: `I loved this dress so much as soon as I tried it on I knew I had to buy it in another color. I am 5'3 about 155lbs and I carry all my weight in my upper body. When I put it on I felt like it thinned me put and I got so many compliments.`,
  },
  {
    id: 2,
    image: images.userImage,
    name: 'Jones Brown',
    date: 'September 21, 2021',
    rating: 5,
    message: `I loved this dress so much as soon as I tried it on I knew I had to buy it in another color. I am 5'3 about 155lbs and I carry all my weight in my upper body. When I put it on I felt like it thinned me put and I got so many compliments.`,
  },
  {
    id: 1,
    image: images.user2,
    name: 'Matilda Brown',
    date: 'August 14, 2019',
    rating: 4,
    message: `I loved this dress so much as soon as I tried it on I knew I had to buy it in another color. I am 5'3 about 155lbs and I carry all my weight in my upper body. When I put it on I felt like it thinned me put and I got so many compliments.`,
  },
  {
    id: 2,
    image: images.userImage,
    name: 'Jones Brown',
    date: 'September 21, 2021',
    rating: 5,
    message: `I loved this dress so much as soon as I tried it on I knew I had to buy it in another color. I am 5'3 about 155lbs and I carry all my weight in my upper body. When I put it on I felt like it thinned me put and I got so many compliments.`,
  },
];
