import {Colors, FontFamily, FontSize} from '@/Theme/Variables';
import {StyleSheet, Dimensions} from 'react-native';
const {height, width} = Dimensions.get('window');
const styles = StyleSheet.create({
  headerText: {
    fontSize: FontSize.regular,
    color: '#000',
    fontWeight: '600',
    alignSelf: 'center',
    padding: 10,
    fontFamily: FontFamily.semiBold,
  },
  midHeading: {
    fontSize: FontSize.medium,
    color: '#000',
    fontWeight: '600',
    alignSelf: 'center',
    paddingTop: 20,
    fontFamily: FontFamily.semiBold,
  },
  bottomText: {
    fontSize: FontSize.small,
    color: '#000',
    fontWeight: '600',
    alignSelf: 'center',
    fontFamily: FontFamily.regular,
  },
  header: {
    height: height * 0.1,
    backgroundColor: Colors.pink,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    marginHorizontal: 20,
    tintColor: Colors.black,
  },
  btnStyle: {
    width: width * 0.9,
    height: height * 0.0685,
    backgroundColor: Colors.heading,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnTitle: {
    color: Colors.white,
    fontSize: FontSize.medium + 1,
    fontWeight: '700',
    fontFamily: FontFamily.bold,
  },
  container: {
    marginVertical: 10,
    alignItems: 'center',
  },
  heading: {
    fontSize: FontSize.regular,
    color: Colors.black,
    fontWeight: '600',
    alignSelf: 'center',
    alignItems: 'center',
    fontFamily: FontFamily.bold,
  },
  subHeading: {
    fontSize: FontSize.small + 1,
    color: Colors.black,
    fontWeight: '300',
    alignSelf: 'center',
    alignItems: 'center',
    fontFamily: FontFamily.regular,
  },
  title: {
    fontSize: FontSize.regular - 2,
    color: Colors.black,
    fontWeight: '600',
    fontFamily: FontFamily.bold,
  },
  listSpace: {
    padding: 10,
    alignItems: 'center',
  },
  listView: {},
  listStyle: {
    width: width * 0.275,
    height: height * 0.0425,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.black,
  },
  listText: {
    color: Colors.black,
    fontSize: FontSize.medium,
    fontWeight: '300',
    fontFamily: FontFamily.regular,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    // height: height * 0.15,
    backgroundColor: Colors.white,
    paddingVertical: 10,
  },
  text: {
    fontSize: FontSize.medium,
    fontWeight: '600',
    fontFamily: FontFamily.bold,
    color: Colors.heading,
    textAlign: 'center',
  },
  calendar: {
    width: width,
    height: height * 0.485,
    backgroundColor: Colors.black,
  },
  theme: {
    backgroundColor: Colors.black,
    calendarBackground: Colors.black,
    textSectionTitleDisabledColor: Colors.white,
    agendaDayTextColor: Colors.white,
    todayTextColor: Colors.white,
    dayTextColor: Colors.white,
    textDisabledColor: Colors.lightGray,
    // textDisabledColor: Colors.gray,
    selectedDayBackgroundColor: Colors.error,
    arrowColor: Colors.white,
    textColor: Colors.error,
    monthTextColor: Colors.white,
  },
  customStyles: {
    container: {
      backgroundColor: Colors.white,
    },
    text: {
      color: Colors.black,
      fontWeight: 'bold',
    },
  },
  headerStyles: {
    backgroundColor: Colors.black,
  },
  box: {
    height: height * 0.15,
  },
  calHeading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 25,
    paddingBottom: 15,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.lightGray,
  },
  calText: {
    fontWeight: '600',
    textAlign: 'center',
    color: Colors.black,
    fontSize: FontSize.medium + 2,
    fontFamily: FontFamily.bold,
  },
  dateBox: {
    paddingVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calButton: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    marginRight: 7.5,
    tintColor: Colors.black,
  },
  bottom: {
    height: height * 0.225,
    backgroundColor: Colors.black,
  },
  timeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 25,
  },
  timerCard: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: Colors.white,
  },
  timer: {
    fontWeight: '600',
    textAlign: 'center',
    color: Colors.white,
    fontSize: FontSize.medium + 2,
    fontFamily: FontFamily.semiBold,
  },
  timerFooter: {
    position: 'absolute',
    bottom: 15,
    width: '100%',
    // height: height * 0.15,
    backgroundColor: Colors.black,
    paddingVertical: 10,
  },
});

export default styles;
